### ISSUE TITLE
Ca'nt connect to Fake AP test my wifi network - bug create multiple Fake AP and conntect not working

### ISSUE THREAD

**Issue by Mrvu182hp** [FluxionNetwork/fluxion#405] opened 2018-02-25 11:30 UTC
please help me how to fix problem i ca'nt  connect to fake AP test my wifi network.
test on linux mint 18 
TP-Link TLWN722N
1] wlan0    [+] Atheros Communications, Inc. AR9271 802.11n
[1] All channels (2.4GHz)
[2] Handshake Snopper Acquires WPA/WPA2 encryption hashes
[2] aireplay-ng deauthentication (aggressive)
1] pyrit verification (recommended)
[1] Every 30 seconds (recommended).
[2] Synchronously (recommended).
[1] Captive Portal Creates an "evil twin" access point.
2] wlan0    [+] Atheros Communications, Inc. AR9271 802.11n
1] Rogue AP - hostapd (recommended)
[Y/N] ..Y
[1] pyrit verification (recommended)
[1] Create an SSL certificate
Handshake Snooper attack completed..
i ca'nt connect to fake AP 

aircrack-ng:
  Installed: 1:1.2-0~beta3-4
  Candidate: 1:1.2-0~beta3-4
  Version table:
 *** 1:1.2-0~beta3-4 500

`fluxion/scripts $ ./diagnostics.sh wlan0
[ FLUXION Info ]
FLUXION V3.11

[ BASH Info ]
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan0) Info ]
Device: phy1
Driver: ath9k_htc
Chipset: Atheros Communications, Inc. AR9271 802.11n
Injection Test: socket(PF_PACKET) failed: Operation not permitted
This program requires root privileges.
failed

[ XTerm Info ]
Version: XTerm(322)
Path: /usr/bin/xterm
Test: 
`
BUG..
![screenshot_20180225-171944](https://user-images.githubusercontent.com/13382998/36640972-05d0c4a6-1a5b-11e8-8d89-e61ee6641880.png)

**Comment by hammi1** [comment] 2018-02-25 15:04
I have this exact same problem. Using ALFA AWUS036NH. I used hostapd, same as everything above (but obviously different wireless chipset, mine is Ralink Technology, Corp. RT2870/RT307.

I do not have multiple AP's showing, just one open one but just stuck on Obtaining IP Address on my Android device (only one I have access to at the moment).

**Comment by minanagehsalalma** [comment] 2018-03-01 22:33
@Mrvu182hp try it on wifislax os

**Comment by deltaxflux** [comment] 2018-03-02 12:26
This bug is not caused by the script more likely it is caused by the environment. However it is very hard to debug. I use also ALFA AWUS036NH which is working fine so it not chipset.  Do I miss the os which you are using or do you don't provide these information?

**Comment by hammi1** [comment] 2018-03-02 12:40
I use Linux Mint 18.3, all packages are up to date. Everything else works apart from this issue, I read somewhere on GitHub that this issue was caused by dhcpd, but I have updated it to the latest version and have the same problem.

**Comment by minanagehsalalma** [comment] 2018-03-02 12:56
Follow my advice and try it on wifislax

**Comment by deltaxflux** [comment] 2018-03-02 12:57
Well, another guy has the same problem. He also used Linux Mint 18.3. It is likly because of your operating system but I don't know where the problem in deep is. Don't listen to @minanagehsalalma. He don't know what he is talking about.

**Comment by hammi1** [comment] 2018-03-02 15:00
It seems that this problem lies within the DHCP server running with Fluxion. Is it worth trying with Kali and seeing if I can connect this way? I am downloading the ISO now to run on a live install, so maybe there are inconsistencies in the version of dhcpd or another problem.

If it works with Kali, and both dhcpd versions are up to date, it must be something in Mint that stops it from working...

**Comment by minanagehsalalma** [comment] 2018-03-02 15:31
Ok tell me when it works

**Comment by deltaxflux** [comment] 2018-03-02 16:43
And if it works please share the dhcp version on your linux mint. So I can add this in the wiki.

**Comment by hammi1** [comment] 2018-03-02 19:02
I tested it in Kali Live - works perfectly. I didn't even have the problem about virtual interfaces (Another problem altogether, i might make an issue about this)
I typed dhcpd into terminal and it gave the values:
DHCPD version of Kali: 4.3.5 
DHCPD version of Mint: 4.3.3

I have updated the isc-dhcp-server in mint to the latest one and it is still 4.3.3, i guess the Kali repos have a newer one.

**Comment by minanagehsalalma** [comment] 2018-03-02 23:53
Great news..  Close the issue know bro as it's not Necessary know.

**Closed** 2018-03-03 11:00 UTC

**Comment by deltaxflux** [comment] 2018-03-03 18:10
@hammi1 can you please provide the hostapd version on both systems?

**Comment by hammi1** [comment] 2018-03-04 16:15
Hostapd of Linux mint: v2. 4

Hostapd version of Kali: v2. 6

Also note that both OSes have been apt updated and upgraded (to each their own repos obviously)

I'm having a problem updating isc-dhcp server to 4.3.5 on my Mint install, it's reporting the latest version of 4.3.3, but on launchpad, it's showing 4.3.5 as the latest one for the Ubuntu repo (which AFAIK is the repo on my Mint install).

I'm not really hoping to download the newer version and compile manually just to see if it works and risk breaking something else on my main Mint install so I will use Kali for the captive portal for the time being.

**Comment by jsRuner** [comment] 2023-03-27 08:54
i meet too,  so what to do?

**Comment by cjb900** [comment] 2023-03-27 14:37
@jsRuner instead of just saying you have the same issue. Please open a new issue and fill out the issue template so we know your setup and the exact issue you are having.
