### ISSUE TITLE
with the new fluxion update it no longer works

### ISSUE THREAD

**Issue by gearcapitan** [FluxionNetwork/fluxion#479] opened 2018-04-26 00:46 UTC
the problem is easy to visualize, the problem is that I can not connect to the fake ap, that is disconnected, my cell phone can not even get an ip address, it is as if fluxing instead of expelling the clients of the original ap, expels them from the fake ap

**Comment by rad4day** [comment] 2018-04-26 01:27
Can't reproduce. Can't give you any advice but "have you tried turning it off and on again?". Having no detailed information sucks.

**Comment by gearcapitan** [comment] 2018-04-26 01:30
Yes, I tried with two phones and the result is the same, neither of them can be connected, this happens to me from the last update, but soon I will see if I can reproduce the error, I use a mini lap to practice then record and others this something complicated.

**Comment by MPX4132** [comment] 2018-04-26 03:58
@gearcapitan Are you referring to fluxion 4.6, or the latest commit? As far as I'm concerned, 4.6 has been working fine. Maybe the latest commit introduced some bugs, but I doubt it, since I only touched the updater and that doesn't affect much.

**Comment by deltaxflux** [comment] 2018-04-26 06:59
I don't think that the auto update is related to your problem. Please execue the diagnostic script.

**Comment by gearcapitan** [comment] 2018-04-26 18:11
yes, I'm using version 4.6, and in fact download and insatale from scratch

**Comment by MPX4132** [comment] 2018-04-27 09:05
Can anyone else reproduce what @gearcapitan claims?

**Comment by MPX4132** [comment] 2018-04-28 11:08
Seems like nobody confirmed it. I'm closing this as an isolated case. If you can show proof, we can reopen the bug.

**Closed by MPX4132** 2018-04-28 11:08 UTC

**Comment by gearcapitan** [comment] 2018-04-28 14:58
in the screenshots I try to show how many problems there are to connect to the fake network, and even so when you manage to connect the page to put the password of the wifi network does not load


https://www.youtube.com/watch?v=QRiNtkkkXws
![photo5127457599099348925](https://user-images.githubusercontent.com/13740942/39397759-268b1e72-4aca-11e8-951a-95a8379a982b.jpg)
![photo5127457599099348926](https://user-images.githubusercontent.com/13740942/39397762-27569b7e-4aca-11e8-8a5e-93575f5b6234.jpg)
![photo5127457599099348927](https://user-images.githubusercontent.com/13740942/39397763-2886cece-4aca-11e8-8fc4-5df10cddccdb.jpg)
![photo5127457599099348928](https://user-images.githubusercontent.com/13740942/39397764-297b3b6c-4aca-11e8-9dfb-50b00268689a.jpg)
![photo5127457599099348929](https://user-images.githubusercontent.com/13740942/39397766-2b113e36-4aca-11e8-812d-32313ba7cd53.jpg)

**Comment by MPX4132** [comment] 2018-04-28 16:38
@gearcapitan Thanks for giving us some info to work with. Have you tired the attack with another device and does it behave exactly like the android phone on the video?

**Comment by gearcapitan** [comment] 2018-04-28 17:10
if exact, I mean the phones take a long time to connect and when they connect they do not connect to the DNS or anything is as if they did not have a network

**Comment by MPX4132** [comment] 2018-04-28 20:10
@gearcapitan Are you by any chance using `airbase-ng`? If you are, that thing's a hack-job and behaves exactly like you mentioned. It works sometimes, sometimes it doesn't because it uses monitor-mode to emulate master-mode. If you had filled the issue template I wouldn't have had to ask this question.
