### ISSUE TITLE
airmon-ng compatibility problem

### ISSUE THREAD

**Issue by h4cx3r** [FluxionNetwork/fluxion#64] opened 2017-08-11 19:36 UTC
### Do you want to request a *feature* or report a *bug*?
-> *Bug*

----

### What is the current behavior?
-> *Hey buddy I am very sad about my problem that I am trying to Hack Wifi with Fluxion 3 on wifislax with my TL-422G USB adapter. But when I tries to start the attack an error occurred with the message that "Your wireless card is not supported Do you want to continue? Y/N" and then I am unable to perform the attack. Even I have Hacked many wifi before with the same wifi adapter on the old version of fluxion but it gives the error only on the latest version of Fluxion only. I wished that i could perform attack with the latest version of fluxion. If my Wifi adapter is not supported only on latest version of Fluxion then Please tell me what to do? how I can perform my attack on latest fluxion please tell me the solution. Waiting for your response continuously..... Your biggest fan! :) *

---

#### Wireless adapter:
*I have TP link adapter: TL-WN422G, driver: nl80211 .*

#### Fluxion version:
*Latest version of fluxion 2 and 3 is giving me an error `

#### Linux version:
*I am using Wifislax 14.00 something. And I have also tried on Kali linux 2016`

**Comment by MPX4132** [comment] 2017-08-11 20:34
Fluxion is on version 3 now, you can download it from here. If running it regularly doesn't work, you can try to run "export FLUXIONDropNet=1" before running fluxion v3, to kill any processes that might interfere with operations:

Go to Fluxion's directory and run:
export FLUXIONDropNet=1; ./fluxion

Make sure you're using this tool legally.

**Comment by h4cx3r** [comment] 2017-08-11 21:46
Thanks Bro! but this also didn't worked for me. I just tested it on Fluxion 3 with many hopes but all in vain :/ . The same error occurred that the wireless card is not supported. I don't why it doesn't supporting my wireless card. Whats the problem :(( Some body help please.

**Comment by MPX4132** [comment] 2017-08-11 22:31
Make sure your wireless card supports injection, as super user, run:
```
aireplay-ng --test wlanX
```
Look for "Injection is working!" If it doesn't come up, then something changed with your driver.
To undo the wlanX monitor interface, as super user, run:
```
ifconfig wlanX down
iwconfig wlanX mode managed
ifconfig wlanX up
```

**Comment by strasharo** [comment] 2017-08-12 05:30
What's the chipset? Are you able to bring it in monitor mode manually and inject with it?

**Comment by MPX4132** [comment] 2017-08-13 04:02
He might be using dash or something other than bash. Some of the parsing commands I used are bash-only, and require bash 4.0 or greater.

**Comment by h4cx3r** [comment] 2017-08-13 05:45
Here is the log file of the error
" curl: (6) Couldn't resolve host 'raw.githubusercontent.com'
lo        no wireless extensions.

eth0      no wireless extensions.

eth1      no wireless extensions.

rmmod: ERROR: could not remove 'AR9271': No such file or directory
rmmod: ERROR: could not remove module AR9271: No such file or directory
modprobe: FATAL: Module AR9271 not found in directory /lib/modules/4.4.16-smp-wifislax

wlan0     IEEE 802.11bgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off "

Only fluxion 0.23 rev 30 works fine on my Wireless adapter.

**Comment by deltaxflux** [comment] 2017-08-13 07:12
Can you also provide the output from airmon-ng ?

**Comment by h4cx3r** [comment] 2017-08-14 11:29
Sure. Here is the output of airmon-ng
Interface       Chipset         Driver

wlan0           Atheros AR9271  ath9k - [phy0]

**Comment by h4cx3r** [comment] 2017-08-14 11:29
Interface                 Chipset                        Driver

wlan0                  Atheros AR9271           ath9k - [phy0]

**Comment by h4cx3r** [comment] 2017-08-14 11:31
Interface    ------   Chipset    ------     Driver

wlan0    ------       Atheros AR9271 ------ ath9k - [phy0]

**Comment by h4cx3r** [comment] 2017-08-14 11:32
Sure. Here is the output of airmon-ng
Interface ------ Chipset ------ Driver

wlan0 ------ Atheros AR9271 ------ ath9k - [phy0]

**Comment by h4cx3r** [comment] 2017-08-14 11:33
Sure. Here is the output of airmon-ng
" Interface ------ Chipset ------ Driver

wlan0 ------ Atheros AR9271 ------ ath9k - [phy0] "

**Comment by MPX4132** [comment] 2017-08-14 11:33
Did you modify the output at all, or did airmon-ng print it out like that?

**Comment by MPX4132** [comment] 2017-08-14 11:38
What's your version of airmon-ng? You can check with:
```
$ man airmon-ng
```
Scroll to the very bottom of the manual. It seems like you're using an outdated version.

**Comment by h4cx3r** [comment] 2017-08-14 13:20
@MPX4132 Yes I did modified the output. I thought that it would be better to understand. Sorry.
Here is the original output of airmon-ng : "
Interface       Chipset         Driver

wlan0           Atheros AR9271  ath9k - [phy0]
"
And I am unable to check the version of airmon-ng. When I enter the command "man airmon-ng" the out put comes that " No manual entry for airmon-ng ".
What to do now? Please keep respounding and helping maybe problem get fix. Never giveup.
Note: I also tried fluxion 3 latest of Kali linux 2017 latest but I am also getting the same error on Kali linux.

**Comment by deltaxflux** [comment] 2017-08-14 14:18
Well if no airmon-ng entry exists to use the aircrack man page. 
```man aircrack-ng | grep Version  ```

Well I found an article that your network adapter is not compartible. To confirm this, we check if the adapter supports injection.
```aireplay-ng --test wlanX```

So in your case
```aireplay-ng --test wlan0```

You should see an output like:
```
ioctl(SIOCSIWMODE) failed: Device or resource busy
16:16:47  Trying broadcast probe requests...
16:16:47  Injection is working!
16:16:49  Found 2 APs
```

**Comment by h4cx3r** [comment] 2017-08-14 14:57
Absolutely, I am getting the output of " aireplay-ng --test wlan0" same like you:

```
ioctl(SIOCSIWMODE) failed: Device or resource busy
19:50:59  Trying broadcast probe requests...
19:50:59  Injection is working!
19:51:01  Found 4 APs
```
Now in this case what is the solution?

**Comment by deltaxflux** [comment] 2017-08-14 15:08
And which airmon / aircrack version do you have?

**Comment by h4cx3r** [comment] 2017-08-14 15:38
I don't know which version I have. And I also don't  know how to check it. And I don't know how to update it. So please don't mind and lead me :)

**Comment by N3V0N** [comment] 2017-08-14 15:42
`apt-cache policy airmon-ng`
Paste the output

**Comment by deltaxflux** [comment] 2017-08-14 15:47
I wrote:

> Well if no airmon-ng entry exists to use the aircrack man page.
man aircrack-ng | grep Version

**Comment by h4cx3r** [comment] 2017-08-14 15:50
out put of "apt-cache policy airmon-ng" :
`bash: apt-cache: command not found`
out put of "man aircrack-ng | grep Version" :+1: 
`No manual entry for aircrack-ng`

**Comment by deltaxflux** [comment] 2017-08-14 16:54
This is was meant for your kali machine

**Comment by MPX4132** [comment] 2017-08-14 17:36
Yeah, the problem is an outdated version of airmon-ng. His output differs from what the program is looking to parse.

**Comment by h4cx3r** [comment] 2017-08-14 17:55
How can I fix that? Is there any way available? or I should bought a new wifi adapter?
Is the problem in my Wifi USB adapter? or in Operating system?

**Comment by MPX4132** [comment] 2017-08-14 18:00
You just need to update your airmon-ng version. If you want to fix it yourself, open fluxion with a text editor and look for these lines (around line 490):
```
		WIAvailable[i]=$(echo "$data" | awk -F':_:' '{print $2}')
		WIAvailableInfo[i]=$(echo "$data" | awk -F':_:' '{print $4}')
```
And change the numbers 2 and 4 to 1 and 2:
```
		WIAvailable[i]=$(echo "$data" | awk -F':_:' '{print $1}')
		WIAvailableInfo[i]=$(echo "$data" | awk -F':_:' '{print $2}')
```
The reason I'm telling you to fix it yourself is because I don't know if we support older versions of airmon-ng. If we do support older versions, we can fix it up, otherwise we won't be able to fix it for you.

**Comment by h4cx3r** [comment] 2017-08-14 18:26
@MPX4132 I did it bro. but it did'nt worked for me.
If you don't mind can you tell me how can i update my airmon-ng to newer version?

**Comment by deltaxflux** [comment] 2017-08-14 18:48
On wifislax:
```
slackpkg update
slackpkg install-new
slackpkg upgrade-all
slackpkg clean-system
```

**Comment by deltaxflux** [comment] 2017-08-14 20:15
Not a bug related to fluxion. Closing...

**Closed by deltaxflux** 2017-08-14 20:15 UTC
Labels: bug

**Comment by evilced** [comment] 2017-08-17 18:46
HI @deltaxflux  I'm seemingly experiencing the same problem than @h4cx3r 

i had 

root@Silver-Queen:/home/Cédric# man aircrack-ng | grep Version
       GNU General Public License, Version 2 or any later version published by
Version 1.2-rc4                  February 2016                  AIRCRACK-NG(1)
root@Silver-Queen:/home/Cédric# aireplay-ng --test wlan0
ioctl(SIOCSIWMODE) failed: Device or resource busy
19:41:36  Trying broadcast probe requests...
19:41:36  Injection is working!
19:41:38  Found 1 AP 

19:41:38  Trying directed probe requests...
19:41:38  94:FE:22:9A:5B:A3 - channel: 8 - 'White Queen'
19:41:38  Ping (min/avg/max): 0.777ms/6.583ms/18.405ms Power: -19.87
19:41:38  30/30: 100%

root@Silver-Queen:/home/Cédric# lspci | grep -i wireless
03:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8723BE PCIe Wireless Network Adapter

**Comment by MPX4132** [comment] 2017-08-17 22:04
I had to put upgrading the installer on hold, this seems like a more important issue right now. It turned out to be more time consuming than I anticipated. I'm working on a solution to make fluxion airmon-ng independent. I'm using bits of their source, so all credit goes to them.

**Comment by deltaxflux** [comment] 2017-08-18 04:44
Open a new issue, please.
