### ISSUE TITLE
Frozen screen with a error message: "cp: cannot stat '/root/fluxion/attacks/Captive Portal/sites/.portal': No such file or directory".

### ISSUE THREAD

**Issue by ighrdm** [FluxionNetwork/fluxion#422] opened 2018-03-13 17:23 UTC
----

Thanks for your time & your efforts.
### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
*Yes*

### Do you want to request a *feature* or report a *bug*?
*Bug*

### What is the current behaviour?
**Frozen screen with a error message:**
_"cp: cannot stat '/root/apps/fluxion/attacks/Captive Portal/sites/.portal': No such file or directory
[*] Starting Captive Portal access point service..."_

### If the current behaviour is a bug, please provide the steps to reproduce it.

NB. I clone all GITs in _"/root/apps"_ directory (_on this exemple "/root/apps/fluxion"_)

![screenshot from 2018-03-13 16-18-03](https://user-images.githubusercontent.com/30585188/37354738-3f5f72f4-26da-11e8-9a16-7a3235b50980.png)
![screenshot from 2018-03-13 16-53-12](https://user-images.githubusercontent.com/30585188/37356994-31064f02-26df-11e8-8d0c-000df0406339.png)
![screenshot from 2018-03-13 16-22-49](https://user-images.githubusercontent.com/30585188/37355011-df482234-26da-11e8-911a-deeb1cf31b67.png)
![screenshot from 2018-03-13 16-23-54](https://user-images.githubusercontent.com/30585188/37355056-f6c9da7e-26da-11e8-98ee-a0f773da52a0.png)

### ***...And after capturing a Handshake and was being successfully verified by pyrit...***

![screenshot from 2018-03-13 16-32-18](https://user-images.githubusercontent.com/30585188/37355726-53c8d954-26dc-11e8-8774-767b27a26d91.png)
![screenshot from 2018-03-13 16-35-58](https://user-images.githubusercontent.com/30585188/37355876-a925af9e-26dc-11e8-97fd-349933794a8a.png)
![screenshot from 2018-03-13 16-38-04](https://user-images.githubusercontent.com/30585188/37356022-f2d72be0-26dc-11e8-96e1-f07a64bf083a.png)
![screenshot from 2018-03-13 16-38-39](https://user-images.githubusercontent.com/30585188/37356058-05fdbcc0-26dd-11e8-9b44-90d5caec69df.png)
![screenshot from 2018-03-13 16-39-29](https://user-images.githubusercontent.com/30585188/37356105-260928b0-26dd-11e8-9079-01cc0456175e.png)

### ***Finaly I Get this message on a frozen screen :***
![screenshot from 2018-03-13 16-40-11](https://user-images.githubusercontent.com/30585188/37356211-5bb2c2e6-26dd-11e8-8ca1-e0ca3bd764d8.png)

### What do you think the expected behaviour should be?

**with:**
**1-** Adapter able to monitoring and injecting
**2-** All fluxion dependencies are auto-installed with > git clone **--recursive** https://github.com/FluxionNetwork/fluxion.git
**3-** And, just in case:
Submodules cloned in fluxion's root directory with the following command:
_git submodule update --init --recursive_
I also download manually the sites from the [sites' repository](https://github.com/FluxionNetwork/sites) and extract them into: _fluxion/attacks/Captive Portal/sites/_

It Should attempts to retrieve the target access point, but bug happens.

### If this is a feature request, what is the motivation or use case for the added feature?
This is not a feature request.

### Specs
![screenshot from 2018-03-13 16-00-53](https://user-images.githubusercontent.com/30585188/37353920-55186daa-26d8-11e8-9d2c-b4e6469c552d.png)

#### FLUXION Info
FLUXION V4.4

#### BASH Info 
GNU bash, version 4.4.18(1)-release (i686-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash

#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** rtl8187
**Chipset:** Realtek Semiconductor Corp. RTL8187
**Master Modes** Yes
**Injection Test:** Injection is working!

#### XTerm Infos
**Version:** XTerm(331)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

#### System Info
**Chipset:** Linux version 4.14.0-kali3-686-pae (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-3)) #1 SMP Debian 4.14.17-1kali1 (2018-02-16)

-----

**Comment by deltaxflux** [comment] 2018-03-13 21:45
Well, I take a look on it but it looks like that more people have this particular problem. I hoped that it is resolved with this commit:  dc0ab6d855d6e5d4bc443e17cf84eacc6b1f8583 

**Can you please check it out?**

**Comment by ighrdm** [comment] 2018-03-13 23:11
Yeah, me too, I hoped cloning or extracting sites would solve the problem.
Let me know, guys, if you need any diagnostic.

Good luck & Thanks.

**Comment by MPX4132** [comment] 2018-03-13 23:34
I'm working on an issue I discovered while working on this one. 

I'll get to working on this one in just a bit lol.

**Comment by MPX4132** [comment] 2018-03-14 00:49
Ok, seems like the issue is caused by the assumption that the user will select a custom portal rather than a generic portal. I think I wrote that part a couple of months ago, I'm working adding comments around the are of the issue to prevent the same mistake. I'll try to have it ready, and push the fix in just a bit.

**Comment by MPX4132** [comment] 2018-03-14 01:53
I've just pushed [a commit](https://github.com/FluxionNetwork/fluxion/commit/6792fedc393d04357de3935b8e138938949975ca), please check out again and verify the bug's been fixed.

**Comment by ighrdm** [comment] 2018-03-14 03:18
***Steps I did:***

**1.** git clone --recursive https://github.com/FluxionNetwork/fluxion.git
**2.** download manually the sites from the [sites' repository](https://github.com/FluxionNetwork/sites) and extract them into: _fluxion/attacks/Captive Portal/sites/_
**3.** Lunch fluxion with all adequate dependencies
**4.** Select SSID target + Handshake already captured + successful pyrit verification
**5.** Lunch attack with SSL Certificate with disconnection of target connected devices
**6.** Select Generic French Language in Captive Portals

But unfortunately, I **still** have a frozen screen **but** this time **without** the message error (see pic below).

![screenshot from 2018-03-14 02-51-30](https://user-images.githubusercontent.com/30585188/37381567-c4b30fc8-2735-11e8-8eb6-953c3505e9b3.png)

**Comment by ighrdm** [comment] 2018-03-14 03:32
I even tried to select a **Custom Portal** rather than a **Generic Portal** but the same problem.

![screenshot from 2018-03-14 03-29-16](https://user-images.githubusercontent.com/30585188/37381945-f17305de-2737-11e8-9bfb-f42b65d995d8.png)

**Comment by MPX4132** [comment] 2018-03-14 05:46
@ighrdm it appears your wireless device has a bad driver. If you go to the issues section and look up “RTL8187” you’ll see everyone with that driver has the same issue. I suggest checking out those closed issues to see how they resolved it, or you could try to open a new issue specifically asking for help with that. I’m closing this issue since the error that was being demonstrated above has been fixed.

You can also try following [this guide](https://github.com/FluxionNetwork/fluxion/wiki/Starting-access-point-hangs!) to check if your driver supports virtual interfaces, because it seems that’s your problem.

**Closed by MPX4132** 2018-03-14 05:46 UTC
Labels: Priority: High, Status: In Progress
