### ISSUE TITLE
Captive Portal not working propeply

### ISSUE THREAD

**Issue by royrey** [FluxionNetwork/fluxion#303] opened 2017-12-12 19:07 UTC
Do you want to request a *feature* or report a *bug*?
Bug

 What is the current behaviour?
fluxion crashes

If the current behaviour is a bug, please provide the steps to reproduce it.
On Windows: It works but you have to enter the access point  manually it doesn't connect automatically after disconnecting from the original wifi.
On Android: -First,it doesn't connect automatically to the access point after disconnecting from the original wifi,you have to connect to it manually.
                   -Second: After connecting to the access point(manually),the portal doesn't open automatically so i have to enter any browser (google chrome for example) but a page appear says that : (Your Connection is not private
Attackers might be trying to steal your information from www."any site".com (for example,passwords,messages,or credit cards).
NET::ERR_CERT_AUTHORITY_INVALID )

What do you think the expected behaviour should be?
That in windows: It should connect to the access point automatically
and in android: It should connect to the access point automatically and direct the client to the page where he have to put with password and make the (Your connection is not private...)page disappear.

Please solve this problem

**Comment by evgeniy4587** [comment] 2017-12-12 21:23
**royrey**

https://github.com/FluxionNetwork/fluxion/wiki/FAQ#clients-are-not-automatically-connected-to-the-fake-access-point

**Comment by MPX4132** [comment] 2017-12-12 22:45
Yeah, clients aren’t supposed to connect automatically. About the cert error, you need to run the attack with SSL disabled.

**Comment by MPX4132** [comment] 2017-12-12 22:47
You should also select connectivity disconnected, not emulated. We can’t really do much about auto connecting, though. I’ll have to close this because it’s expected behavior.

**Closed by MPX4132** 2017-12-12 22:47 UTC

**Comment by M1z23R** [comment] 2017-12-13 14:31
Me again :)
I don't want to start an issue since it's not related to you directly. As i said in someone of the issues i started working on my own FluxRpi script. So far i am doing good, i am using dnsmasq instead of dhcpd server and everything works fine except for one crucial thing, html php form (index.html) doesn't send data to check.php, for some reason when i use this https://www.w3schools.com/php/php_forms.asp as a template, it goes through and writes password attempts to .txt files, but with your javascript page it doesn't and i can't trace it, so far i only noticed that your check.php, authenticator.php and update.php files don't have ?> ending.
