### ISSUE TITLE
UI needs more instructions for the user.

### ISSUE THREAD

**Issue by Geczy** [FluxionNetwork/fluxion#87] opened 2017-08-18 16:12 UTC
### Do you want to request a *feature* or report a *bug*?
-> *Bug*

----

### What is the current behavior?
No message during handshake

---

#### If the current behavior is a bug, please provide the steps to reproduce.
![image](https://user-images.githubusercontent.com/1036968/29467419-79c9afc8-840e-11e7-9117-ed3079777f63.png)

--- 

#### What is the expected behavior?
Inform the user on what's happening so they're not confused

**Comment by MPX4132** [comment] 2017-08-18 18:24
Let's make sure it's doing what I think it's doing. In the screen shot you showed, it looks like you chose the passive mode, correct? If you chose an aggressive mode (forcing deauthentication), and only airodump-ng came up, there's a problem. If you did in fact chose just a passive attack:
* Did the attack stop when a handshake was captured? Stopping, in this sense, is literal. Meaning, airodump-ng halted completely, but the handshake captor window should **not** close. This can be verified by looking at the elapsed field in airodump-ng for a few seconds. If the field stopped updating the attack succeeded and you caught a valid handshake.
* If you choose any option in fluxion, while the snooper attack is in progress, does the handshake captor close? It should, if it does not, it's a bug.
I'm just verifying the behavior, and I understand you would like instructions or a clear sign the attack stopped.

**Comment by Geczy** [comment] 2017-08-18 18:40
1. Yes, passive using pyrit.
2. The captor screen did appear to freeze, elapsed time stopped counting up. But nothing happened in the fluxion terminal.
3. Choosing another option while handshake captor is in progress does not close the captor screen.

Need to give instructions on this screen as well. "please wait..." will just leave the user sitting forever 

![image](https://user-images.githubusercontent.com/1036968/29472629-b09741b4-8422-11e7-9bf3-371af32e710a.png)

**Comment by SwiftPredator** [comment] 2017-08-18 19:27
Got the same bug on all methods.

**Comment by MPX4132** [comment] 2017-08-18 20:24
Did the deauthenticator window close? If it did, and the "Handshake Captor" window froze, it means the attack succeeded. You can verify by checking if the handshake captor window (airodump-ng) says "Handshake Captured" on the top right. You can also check by going into "fluxion/attacks/Handshake Snooper/handshakes/" if you see handshakes there, it succeeded and that's a valid handshake.

**Comment by SwiftPredator** [comment] 2017-08-18 20:53
Its frozen and it don't say "Handshake Captured" on the top right. But there is a .cap file in "fluxion/attacks/Handshake Snooper/handshakes/" after launching the deauthenticator attack.

**Comment by MPX4132** [comment] 2017-08-18 20:56
Then yeah, it succeeded, the attack was successful. If there was no capture file, the attack would've failed. Does it, by any chance, say "fixed channel -1" or something like that?

**Comment by SwiftPredator** [comment] 2017-08-18 20:58
Not in the Handshake Captor or in the fluxion window.

**Comment by SwiftPredator** [comment] 2017-08-18 20:59
![virtualbox_kali-linux-2017 1-vbox-amd64_18_08_2017_22_58_50](https://user-images.githubusercontent.com/20613170/29477488-e0fbd522-8468-11e7-9905-1e261e3b95b7.png)

**Comment by SwiftPredator** [comment] 2017-08-18 21:01
This is the whole outcome after the window froze. I think the same like @Geczy have it.

**Comment by MPX4132** [comment] 2017-08-18 21:04
Oh, I'm sorry. I gave you wrong information. It's actually working perfectly fine from what it looks like in that picture. The handshake captor window should say "WPA Handshake: XXXXXXXXXX" if it caught a handshake. Now you can run the Captive Portal attack by choosing option 1. The captive portal attack will ask you for a handshake and **should auto detect** that you've already captured one and ask you if you want to use it. It'll then verify it and you can start the attack.

**Comment by SwiftPredator** [comment] 2017-08-18 21:07
Ok, did that.Is it normal that it stucks in the output "Starting Captive Portal access point service..."?

**Comment by SwiftPredator** [comment] 2017-08-18 21:07
Thanks for your fast help by the way 💯

**Comment by MPX4132** [comment] 2017-08-18 21:12
Actually, I'm hanging around here to see if the latest update causes issues. It should not get stuck on starting the access point service. If you still have it open, open another terminal and run:
```
# iwconfig
```
And post the results here. It seems like the access point interface dropped or crashed.

**Comment by SwiftPredator** [comment] 2017-08-18 21:28
I just loaded the new version you uploaded and know even the authentication doesn't want to work.
Cant text the Captive Portal now. The Handshake Captor window opens, but the deauthentification doesn't go on.  The handsomer view isn't freezing. It worked in the unready version you uploaded before.
![virtualbox_kali-linux-2017 1-vbox-amd64_18_08_2017_23_27_18](https://user-images.githubusercontent.com/20613170/29478367-d2f6c2b2-846c-11e7-9f80-65c764321ee9.png)

**Comment by SwiftPredator** [comment] 2017-08-18 21:29
Sry, this auto corrector really doesn't do what i want :( Hope you could analyze the problem anyways.

**Comment by MPX4132** [comment] 2017-08-18 21:58
Confirmed, fixing it now.

**Comment by MPX4132** [comment] 2017-08-18 22:03
(Fixed by commit](https://github.com/FluxionNetwork/fluxion/commit/e3ef1110ca609e03ef73e0621359d65ad1ded878), thanks for the report.

**Comment by SwiftPredator** [comment] 2017-08-18 22:29
ifconfig after # iwconfig

![virtualbox_kali-linux-2017 1-vbox-amd64_19_08_2017_00_27_41](https://user-images.githubusercontent.com/20613170/29479976-799e893a-8475-11e7-8c9a-dfd17bdbd709.png)

**Comment by SwiftPredator** [comment] 2017-08-18 22:30
Ah and thanks for bringing the deauth to work again !

**Comment by MPX4132** [comment] 2017-08-18 22:45
Your interfaced dropped out of monitor mode, "wlan0" should be in "Mode:Monitor" like "wlan0FLXap" is.
Try running fluxion with the drop flag, so do:
```
export FLUXIONDropNet=1; ./fluxion
```
It could be that the wireless manager is interfering, but I doubt it. It's probably related to the driver.

**Comment by Geczy** [comment] 2017-08-20 02:15
Don't see why this was closed? The UI was never updated right? User still has no clue how the handshake attack is progressing @deltaxflux

**Comment by deltaxflux** [comment] 2017-08-20 08:43
Because I thought that the problem is fixed after:

> Ah and thanks for bringing the deauth to work again !

I think a good idea is that we print a . if the handshake is not found and + if it is found

Sample output
`.............+`

**Comment by Geczy** [comment] 2017-08-21 14:33
>You can also check by going into "fluxion/attacks/Handshake Snooper/handshakes/" if you see handshakes there, it succeeded and that's a valid handshake.
edit: Sorry, posted this in the wrong thread.

Left this up for several minutes on my own WiFi, it never seems to capture a handshake

It was deauthenticating everyone, but the deauth appears to have stopped and the window closed. Now it's just this one window

![image](https://user-images.githubusercontent.com/1036968/29523806-2b41d902-865c-11e7-9d4d-a77f672045fd.png)

**Comment by deltaxflux** [comment] 2017-08-21 16:56
If the mdk3 or aireplay windows stops the handshake successfully captured

**Comment by Geczy** [comment] 2017-08-21 16:59
Yes i know. But ui needs to update too hence the issue being open

**Comment by LOLLYTHECAT** [comment] 2017-08-25 15:04
Why fluxion stuck on "[*] Starting Captive Portal access point service..." .. ?

**Comment by deltaxflux** [comment] 2017-08-25 15:22
There is a button *new issue* hint hint

**Comment by kram25** [comment] 2017-09-01 10:13
Hi i am also stuck  on staring captive portal access point service.. please help thank you

**Comment by MPX4132** [comment] 2017-09-04 14:27
@gudangboys make sure it’s the **absolute path** not a relative path.

**Comment by gudangboys** [comment] 2017-09-05 02:33
Please correct me if wrong - path specified in Kali from root
/root/Desktop/fluxhandshake/handshake01.cap
Still returns "Hash file does not exist" 
Sorry for the silly questions and thanks

**Comment by MPX4132** [comment] 2017-09-05 04:39
Yeah, that's an absolute path alright. Well, all I can think of is human error somewhere. You sure the cap file doesn't have a hyphen, such as the one below:
```
/root/Desktop/fluxhandshake/handshake-01.cap
```
I highly doubt it's fluxion, I haven't had any issues with the path input. That could just be bias from my part, though. Just double check or triple check everything and report back.

**Comment by gudangboys** [comment] 2017-09-05 06:19
Thanks for your prompt response. 
Would you help me here again please:
1. Am I directing it to an already existing cap file?
2. If so I haven't a cap file, I assume it would write to the file I specify.
3. If not, how do I then create a .cap file to specify the path?
Thanks in advance for your patience

**Comment by anashexor** [comment] 2017-09-08 12:07
I have same problem with gudangboys.. i dont have that .cap file .. how to create it?

**Comment by MPX4132** [comment] 2017-09-08 17:51
Sorry for the super late response @gudangboys I'm not sure what happened with the notification. You just have to run the `Handshake Snooper` attack. The attack will run and once a valid capture file is retrieved, the `Handshake Captor` window will stop, **but it will not close**. You can verify it stopped by checking the "Elapsed" field. Ignore the "Handshake Captured" notification on the top right of the `Handshake Captor` window, it's usually wrong. You can close the `Handshake Captor` window after if you want. Once you have the file, you can go to the main fluxion window and select another attack, the `Captive Portal` attack. Since you used the built-in captor, the script will automatically detect any previously retrieved handshake files and will load them itself.

**Comment by Geczy** [comment] 2017-09-08 18:13
Gotta add this as instruction to the app :)

**Comment by deltaxflux** [comment] 2017-09-10 09:23
I add a UI for the handshake. Try it and share results below.

**Closed** 2017-09-10 19:04 UTC
Labels: Priority: Low, Status: In Progress, Type: Enchantment

**Comment by SkyMesA** [comment] 2017-09-22 11:27
Hello, i'm new with Fluxion! Nice work

But when i try to deauth witk mdk3 ive got this message but nothing happen : 
`Periodiccaly re-reading blacklist/whitelist every 3 secondes`

**Comment by jitu3232** [comment] 2018-01-10 19:06
Fluxion not showing option to select in GUI in nethunter
It is showing choose language but don't show the options.
It shows to select wireless device but do not show option to select.
Please help
