### ISSUE TITLE
Dynamic deauth

### ISSUE THREAD

**Issue by minanagehsalalma** [FluxionNetwork/fluxion#152] opened 2017-09-10 22:23 UTC
please make the jamming interface stop the jamming and start a scan searching for our target (using BSSID) When the script does not find
clients to deauth on the old channel and when there no clients are connected to our rogue ap . and then restart the attack automatic with the new channel ... and a new feature play a ringtone when the script doesn't found the ap after multi scans to warn the script user that the router has been shutdown ...

**Comment by minanagehsalalma** [comment] 2017-09-11 12:07
@deltaxflux

**Comment by deltaxflux** [comment] 2017-09-11 12:54
Maybe an improvement. Priority low, feel free to contribute.

**Comment by minanagehsalalma** [comment] 2017-09-15 12:01
@deltaxflux why Priority is  Low .. it will fix the router restart that destroys the attack ...

**Comment by deltaxflux** [comment] 2017-09-15 13:05
Because I have a leak of time.

**Comment by minanagehsalalma** [comment] 2017-09-15 13:49
@deltax Ok..  But please when you have a spare time add it because it's the
only issue in  fluxion

**Comment by deltaxflux** [comment] 2017-09-15 14:05
Nope its not.

**Comment by MPX4132** [comment] 2017-09-15 18:07
Yeah, I agree with @deltaxflux, the current version could use a lot of polishing. I'm going to start working on it soon. I've been preoccupied with other things lately, which is why I've been rushing changes to the script.

**Comment by minanagehsalalma** [comment] 2017-09-15 20:27
@deltaxflux @MPX4132  please tell me when you finish it 😊😊

**Comment by evgeniy4587** [comment] 2017-11-11 22:45
Hi everyone, I suggest to make it a little bit more smart and less suspicious :) Not long time ago I'm tried fluxion in use. I'm start the script all was fine and I live it for few hours. When I'm came back to laptop and to the monitor window I saw that ORIGINAL access point was turned off and fake access point was work(I know it's ok). Original AP wast turned of fo 2 or 3 hours? then it was turned on. And I think it is very suspicious when owner of the origina AP is turnig off his AP but still see it(Fake AP) on his/her phone for example in list of networks.
That's why I suggest to make Fake AP to stop when Original AP is turned of more than 5 minutes(for example), But still runnin monitoring and probably mdk3. And start again Fake AP when Original AP is turned on. It will be more automatic, and you can live it for whole day and check the resul after 8-10 hours. 
Thank you for attention :)

**Comment by MPX4132** [comment] 2017-11-11 23:10
@evgeniy4587 You should start a new issue with your idea and mark is an an improvement/feature request. I agree with you.

**Comment by evgeniy4587** [comment] 2017-11-11 23:58
Hi MPX4132 , I think @minanagehsalalma is already start righ thread. I just supplemented his/her idea. And also I don't wanna make more tickets for developers ;)

**Comment by evgeniy4587** [comment] 2017-12-10 14:04
If you need some help in testing, I'm ready to test something :)

**Comment by rodrigogs** [comment] 2017-12-26 20:52
+1

This feature would be great!

**Comment by rodrigogs** [comment] 2017-12-26 20:55
For now, my workaround is to have two network cards, one to serve my captive protal and another to keep jamming the AP.

**Comment by minanagehsalalma** [comment] 2017-12-26 21:01
@rodrigogs thanks

**Comment by strasharo** [comment] 2018-02-18 22:27
Duplicate of https://github.com/FluxionNetwork/fluxion/issues/381 , let's track the efforts there.

**Closed by strasharo** 2018-02-18 22:27 UTC
Labels: Priority: Low, Type: Enhancement

**Comment by minanagehsalalma** [comment] 2018-02-27 17:49
@strasharo open the issue again the one you reference.. Not similar  of why i opened the issues...  😑
