### ISSUE TITLE
xterm window missing from handshake snooper

### ISSUE THREAD

**Issue by drjohannspector** [FluxionNetwork/fluxion#289] opened 2017-12-04 06:52 UTC
Anyone else having issues with the capturing data on channel X xterm window appearing? I only have 2/3 of them after running Handshake Snooper. Everything seems to work, I just cant see my target clients, BSSID, etc.

**Comment by MPX4132** [comment] 2017-12-04 07:14
Why did you make another issue about the same thing I closed earlier? I’m closing this soon if you don’t explain. There no reason to keep posting it.

**Comment by MPX4132** [comment] 2017-12-04 07:38
@drjohannspector Hey, are you by any chance talking about fluxion's scanner, and not the handshake snooper? Because it sounds like you're talking about the scanner here. If it is that, let me know so I can remove the duplicate label, and reword the issue's title.

**Comment by drjohannspector** [comment] 2017-12-04 07:46
It was an accident, I apologize. 

No, not the scanner, the airodump xterm window where I can see the AP's MAC, as well as the connected clients.

**Comment by MPX4132** [comment] 2017-12-04 07:57
Well, I got a bit irritated because you ignored what I explained in the other issue you opened. I wrote the entire explanation and you didn't even reply. It's not a bug, I had to remove it because it was causing issues on some systems. Here's the longer explanation I gave you earlier:

https://github.com/FluxionNetwork/fluxion/issues/288

**Comment by drjohannspector** [comment] 2017-12-04 08:00
Understandable, I apologize. I have been messing with this too long for the day. I didn't mean to waste your time. Having some hardware issues today, I actually thought the first post never went through. Will not happen again. Honest mistake

**Comment by MPX4132** [comment] 2017-12-04 08:02
@drjohannspector It's all good man, don't worry about it. There's been instances where people come and start doing that, which, as you might image, is a bit annoying. By the way, you should've gotten the notification, unless you explicitly turned it off. If you're new, the upper right shows a blue dot when you've got a notification.

**Closed** 2017-12-04 08:02 UTC
Labels: duplicate

**Comment by drjohannspector** [comment] 2017-12-04 08:19
@MPX4132 thank you for being understanding. Now I just need to find out how to get the captive portal working, seems I have a pretty typical issue where it just hangs at starting server. Time to do some research. Sounds like this adapter doesn't play well with others...

**Comment by MPX4132** [comment] 2017-12-04 09:02
@drjohannspector It's probably the virtual interfaces problem. Fluxion needs to do two things at once, and older driver don't support that kind of behavior. I think even some new ones don't. I suggest going into the issues section and filtering like this:
"driver_here in:body" or "driver_here in:comments" or "driver_here in:title"

**Comment by drjohannspector** [comment] 2017-12-05 05:09
It's this model, Alfa AWUS051NH, pretty popular model. I realized it uses the same 3070 drivers as what I've already got.

**Comment by MPX4132** [comment] 2017-12-05 06:21
I can’t find anything in the issues about that model, but if it uses the same drivers as another card you’re having trouble with, you’re going to have the same issue(s) with that model.

**Comment by drjohannspector** [comment] 2017-12-05 08:11
Figured as much. I think the issue lies with my DHCP server. It doesn't seem to start...

service isc-dhcp-server start
Job for isc-dhcp-server.service failed because the control process exited with error code.
See "systemctl  status isc-dhcp-server.service" and "journalctl  -xe" for details.

-- Unit isc-dhcp-server.service has begun starting up.
Dec 05 00:10:01 kali isc-dhcp-server[14162]: Launching both IPv4 and IPv6 servers (please configure INTERFACES in /etc/default/isc-dhcp-server if you only want one or 
Dec 05 00:10:01 kali isc-dhcp-server[14162]: Starting ISC DHCPv4 server: dhcpddhcpd service already running (pid file /var/run/dhcpd.pid currenty exists) ... failed!
Dec 05 00:10:01 kali systemd[1]: isc-dhcp-server.service: Control process exited, code=exited status=1
Dec 05 00:10:01 kali systemd[1]: isc-dhcp-server.service: Failed with result 'exit-code'.
Dec 05 00:10:01 kali systemd[1]: Failed to start LSB: DHCP server.
-- Subject: Unit isc-dhcp-server.service has failed

**Comment by drjohannspector** [comment] 2017-12-05 08:13
Maybe this addition of wlan0 may be the ticket?


# Defaults for isc-dhcp-server (sourced by /etc/init.d/isc-dhcp-server)

# Path to dhcpd's config file (default: /etc/dhcp/dhcpd.conf).
#DHCPDv4_CONF=/etc/dhcp/dhcpd.conf
#DHCPDv6_CONF=/etc/dhcp/dhcpd6.conf

# Path to dhcpd's PID file (default: /var/run/dhcpd.pid).
#DHCPDv4_PID=/var/run/dhcpd.pid
#DHCPDv6_PID=/var/run/dhcpd6.pid

# Additional options to start dhcpd with.
#       Don't use options -cf or -pf here; use DHCPD_CONF/ DHCPD_PID instead
#OPTIONS=""

# On what interfaces should the DHCP server (dhcpd) serve DHCP requests?
#       Separate multiple interfaces with spaces, e.g. "eth0 eth1".
INTERFACESv4="wlan0"
INTERFACESv6=""

**Comment by starlonedz** [comment] 2017-12-05 09:52
Hello
Same issue 3rd xtern window not appearing
Ralink3070

**Comment by deltaxflux** [comment] 2017-12-05 15:07
The service is already running

**Comment by MPX4132** [comment] 2017-12-05 22:37
@drjohannspector Can you try the changes and check if that makes a difference? I can't test it with my hardware because I don't get the issues you're getting, neither in `hostapd`, nor `airbase-ng`.

**Comment by deltaxflux** [comment] 2017-12-06 05:13
@MPX4132 it says:
> Dec 05 00:10:01 kali isc-dhcp-server[14162]: Starting ISC DHCPv4 server: dhcpddhcpd service already running (pid file /var/run/dhcpd.pid currenty exists) ... failed!

**Comment by MPX4132** [comment] 2017-12-06 05:26
@deltaxflux Yeah, sorry I didn't notice your message earlier. I also noticed that earlier lol, [here's where I told him.](https://github.com/FluxionNetwork/fluxion/issues/290#issuecomment-349524192)

**Comment by deltaxflux** [comment] 2017-12-06 05:29
Oh sorry I missed that.
