### ISSUE TITLE
Captive Portal wont start on 5 ghz (but works perfectly on 2.4 ghz)

### ISSUE THREAD

**Issue by calee4nyaboy** [FluxionNetwork/fluxion#398] opened 2018-02-18 06:33 UTC
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
Yes

#### Do you want to request a *feature* or report a *bug*?
*Issue*

#### What is the current behaviour?
The captive portal works great in 2.4 ghz but when I run it on a 5 ghz network, it never starts.  I choose which UI (Option 7, generic, english), then it says "captive portal is starting" but none of the six windows show up.  Because it works in 2.4 ghz, it seems there is nothing wrong with the USB card I am using (rt2800usb / Ralink RT5572), but I still went to the troubleshooting page for this issue at:
https://github.com/FluxionNetwork/fluxion/wiki/Starting-access-point-hangs!
As expected, all of the tests ran successfully.  There was one hiccup in the last step which I am not sure if it is important or not.  However, if it *is* important, then I don't see why it wouldn't affect 2.4 ghz (remember, the 2.4 ghz works great).  The issue I'm referring to is while running the last test, in the mdk3 window, it said "read failed: Network is down. wi_read(): Network is down".  It did not say that message immediately after starting the mdk3 command.  The message took about 4 or 5 minutes to show up.  I did the test twice and it took many minutes for that message to show up each time.  I will provide a screen shot of these two tests running simultaneously (mdk3 and hostapd)

#### If the current behaviour is a bug, please provide the steps to reproduce it.

Simply tried to execute the captive portal on a 5 ghz network

#### What do you think the expected behaviour should be?

The captive portal should work showing the six windows.

#### Specs
[ FLUXION Info ]
FLUXION V3.11

[ BASH Info ]
GNU bash, version 4.4.11(1)-release (i686-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Path: /bin/bash

[ Interface (wlan1) Info ]
Device: phy1
Driver: rt2800usb
Chipset: Ralink Technology, Corp. RT5572
Injection Test: No Answer...
Injection is working!

[ XTerm Info ]
Version: XTerm(327)
Path: /usr/bin/xterm
Test: XServer/XTerm success!

[ HostAPD Info ]
hostapd v2.4
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

[ Aircrack-ng Info ]

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

[ System Info ]
Linux version 4.9.0-kali3-686-pae (devel@kali.org) (gcc version 6.3.0 20170321 (Debian 6.3.0-11) ) #1 SMP Debian 4.9.18-1kali1 (2017-04-04)

-----

Thank you for your work and support on this project!!

**Comment by calee4nyaboy** [comment] 2018-02-18 06:35
![20180217_215923-800x618](https://user-images.githubusercontent.com/31833255/36349057-d373226e-1475-11e8-9cf7-65a383dafd9d.jpg)

**Comment by usuarionuevor** [comment] 2018-02-18 20:20
check my request: https://github.com/FluxionNetwork/fluxion/issues/385
at the momment only airgeddon supports 5ghz, no fluxion and no linset.

**Comment by calee4nyaboy** [comment] 2018-02-18 20:54
Oh, that's weird because Fluxion supports scanning 5ghz networks and getting 5ghz handshakes. So I had no idea 5ghz captive portals wouldn't work.  Also, I do not remember seeing this written in the wiki. 

I wish the code would have spit out a small message saying that 5ghz portals aren't supported because I spent hours on this trying to get it to work and troubleshooting it.

Not supporting 5ghz captive portals  is a huge drawback. Is there a work-around? If you use two network cards at the same time will it work?  What do we need to do in order to have 5ghz captive portals?

**Comment by strasharo** [comment] 2018-02-18 22:32
Duplicate of #385

**Closed by strasharo** 2018-02-18 22:32 UTC

**Comment by usuarionuevor** [comment] 2018-02-20 12:02
@calee4nyaboy fluxion is not supposed to warn you about 5ghz since is relatively new technology...

Reason you can get handshakes is because is not fluxion the one who does, remember this is just an automated script and it uses other tools to get handshake, etc... same as it uses aircrack suite like airmon to set monitor mode, etc.

You can do it manually (without fluxion or any automated script) or like I said just use airgeddon it is 'all-in-one' script and have full support for 5ghz to create AP, deauth, and everything.

**Comment by deltaxflux** [comment] 2018-02-20 21:20
It is vivid that you don't have any idea what you are talking about.

**Comment by calee4nyaboy** [comment] 2018-02-20 21:28
@deltaxflux Comments like these are negative and helpful to no one. You'll have to excuse others for not knowing as much as you do. After all, you're the one who created this project so how could others possibly know as much as you do?

This is the opportunity for you to educate others on how things work and to spread knowledge to the rest of the members of this project.

**Comment by calee4nyaboy** [comment] 2018-02-20 21:31
@usuarionuevor Thank you for taking the time to explain how things work and to answer my questions so that I better understand the mechanics of this.

**Comment by deltaxflux** [comment] 2018-02-21 18:19
Well, @calee4nyaboy 
This is not negative. I only hate people who think they no something but in reality it is a total mess.

To your problem:
At the moment 5ghz access points are only accessable on the developer branch. This is still beta and I don't see any purpose to merge this to the master branch yet so be excited.
