### ISSUE TITLE
Unable to start captive portal interface 

### ISSUE THREAD

**Issue by applehacker321** [FluxionNetwork/fluxion#338] opened 2018-01-01 03:48 UTC
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No*

#### Do you want to request a *feature* or report a *bug*?
*Bug*

#### What is the current behaviour?
I am using RT5370n WiFi chipset, have also tried Other interface such as the TLWN722N, but still couldn’t get the captive portal interface to work. The program output: 
“Unable to start captive portal interface”
Then returns to menu. I am using fluxion 3.11 (the latest version), with Ubuntu Mate 16.04.02.

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

-----

**Comment by applehacker321** [comment] 2018-01-01 04:29
Forgot to mention, I have already captured a validated handshake

**Comment by MPX4132** [comment] 2018-01-01 06:47
It seems your device's driver might not support virtual interfaces. You're going to have to check yourself whether the driver supports virtual interfaces or not following [this guide](https://github.com/FluxionNetwork/fluxion/wiki/Starting-access-point-hangs!). I'm going to close this issue because virtual interface support isn't an issue with fluxion, but an issue with your driver. You can continue to reply here to let us know what you find out. Again, it seems the issue isn't related to fluxion. If you can prove me wrong, and determine it's an issue with fluxion, we can reopen the issue.

**Closed by MPX4132** 2018-01-01 06:47 UTC

**Comment by underscrew** [comment] 2018-01-09 03:58
@MPX4132 getting this same problem.
Fluxion worked flawlessly 1 month ago on kali, now i've tried it on my ubuntu and got this error.
Can't be driver problem. Can it?

**Comment by MPX4132** [comment] 2018-01-09 05:57
Wait, so it was working fine before? Yeah, that sounds fishy. Do you by any chance know if there's been an update to the driver you guys are using?

**Comment by MPX4132** [comment] 2018-01-09 05:58
It could also be the network-manager being overly aggressive.

**Comment by underscrew** [comment] 2018-01-09 23:08
@MPX4132 I managed to find the difference on the drivers, on my ubuntu, the version is the `driverversion=4.10.0-42-generic`
and on my kali, which is the one working:
`driverversion=4.9.0-kali3-amd64`

How can i copy the kali driver to my ubuntu? I did a lot of research with no luck.

**Comment by MPX4132** [comment] 2018-01-09 23:17
@underscrew I don't know how to swap or setup drivers, sorry man. Someone else might be able to help, though. From what  I read, you'll have to compile the driver yourself because apparently they're kernel specific (binary-specific).

**Comment by Aoki07** [comment] 2020-07-09 21:13
Hello , i have a problem in the second step in fluxion for to create a "captive portal " this message appears when I select my wifi card :
] Select an interface for the access point.

[1] eth0 [+] Intel Corporation 8254EM Gigabite Ethernet Controller(rev
[2] wlan0 [+] TP-Link TL-WN722N v2
[3] Repeat
[4] Back

[fluxion2@kali]-[~] 2

[*] Unable to start captive portal interface, returning!

can someone Help please?

**Comment by Quang-vip** [comment] 2020-08-01 15:30
@Aoki07 you need to make the adapter run in concurrent mode, I used to face that problem but after enabling concurrent mode, it went fine

**Comment by Aoki07** [comment] 2020-08-02 23:03
Hello thanks for your answer , can you explain me how can do this?

**Comment by Quang-vip** [comment] 2020-08-03 02:18
@Aoki07 first you need to clone this repository: https://github.com/aircrack-ng/rtl8188eus
then open up _include/autoconf.h_

look for `//#define CONFIG_CONCURRENT_MODE` and uncomment it by removing the double forward slash
after that, build the driver then install it

restart your machine (that's what I usually do, you could **hot-remove** the driver then **hot-insert** it so you don't need to restart your machine)
run `ip a` and you should be able to see 2 wireless interfaces (apart from the built-in one if your machine has one)

then choose 1 for jamming and stuff, 1 for access point

now I'm stuck with the fact that my phone nor any other device can't connect to the rogue AP lol

**Comment by Aoki07** [comment] 2020-08-03 03:00
Hello Quang-vip can we speak here?


Quang-vip <notifications@github.com> escreveu no dia segunda, 3/08/2020
à(s) 03:18:

**Comment by Aoki07** [comment] 2020-08-03 03:06
Thanks when i remove the double forward slash how i can build the driver and install again? can we speak in private?

**Comment by Quang-vip** [comment] 2020-08-03 04:35
It's better to talk publicly as the others might need this in the future
just run `make` in the root folder of the repository, then run `sudo make install`
don't forget to install the kernel headers corresponding to your kernel version

**Comment by rajatjoshi98** [comment] 2020-08-28 06:43
hey @Quang-vip i have tried but not working

**Comment by rajatjoshi98** [comment] 2020-08-28 06:43
after install adaptor is not working at all

**Comment by Quang-vip** [comment] 2020-08-28 10:15
> 
> 
> after install adaptor is not working at all

Could you be more specific? What did you do exactly?

**Comment by bharath4865** [comment] 2020-09-07 06:04
you need to make the adapter run in concurrent mode, I used to face that problem but after enabling concurrent mode, it went fine

sir can i please have a talk in private as i to have the same issue and i was a begginer or can u provide any link of an vedio  which helps me

**Comment by bharath4865** [comment] 2020-09-07 06:05
please reply quang-vip fast

**Comment by Quang-vip** [comment] 2020-09-08 02:16
> sir can i please have a talk in private as i to have the same issue and i was a begginer or can u provide any link of an vedio which helps me

like I said, it's better to talk here

**Comment by rajatjoshi98** [comment] 2020-09-08 04:10
its not nessessary to be in concurrent mode.

**Comment by rajatjoshi98** [comment] 2020-09-08 04:13
@Quang-vip i havent face this probleum.
now I'm stuck with the fact that my phone nor any other device can't connect to the rogue AP lol
(Edit: probably because of the DHCP server that fluxion uses)

**Comment by rajatjoshi98** [comment] 2020-09-08 04:16
the probleum that i am facing is in deauthentication. 
it is not sending the packets at faster rate ,so as a result it is unable to deauthentcate properly.

**Comment by Quang-vip** [comment] 2020-09-09 08:37
> 
> 
> the probleum that i am facing is in deauthentication.
> it is not sending the packets at faster rate ,so as a result it is unable to deauthentcate properly.

Try using other deauth methods

**Comment by niiitish** [comment] 2020-12-14 07:19
Just do one thing when you are getting this error remove your adapter and pluging your problem will solve in my case when i remove mode: monitor when i plugin mode:auto

**Comment by anil1143** [comment] 2021-04-30 09:11
> Hello , i have a problem in the second step in fluxion for to create a "captive portal " this message appears when I select my wifi card :
> ] Select an interface for the access point.
> 
> [1] eth0 [+] Intel Corporation 8254EM Gigabite Ethernet Controller(rev
> [2] wlan0 [+] TP-Link TL-WN722N v2
> [3] Repeat
> [4] Back
> 
> [fluxion2@kali]-[~] 2
> 
> [*] Unable to start captive portal interface, returning!
> 
> can someone Help please?

Hello

**Comment by cjb900** [comment] 2021-05-01 18:38
@anil1143 why are you posting to an old long closed issue? 
regarding your actual issue its due to the chipset in the adapter you have not supporting VIF. VIF is needed to be able to both deauth and create a fake AP at the same time. There is no way to give that adapter VIF support either. You would have to look into getting either a second adapter or one that supports monitor mode, AP mode and VIF. 

here is a list of supported adapter/chipsets 
Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8187 <- present in Alfa AWUS036H (2.4Ghz - USB) (may require patched driver)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

**Comment by cjb900** [comment] 2021-10-09 18:03
@anibardo Why are you posting to an issue that is over 3 years old and closed 🤔Second your issue is that the wifi adapter you have does not support VIF so it is not able to deauth and create a fake AP at the same time. You will need to either get a second one to use with fluxion or replace this one all together that supports monitor mode, AP mode and VIF. There is no way to get that adapter to work by its self.

**Comment by anibardo** [comment] 2021-10-10 07:33
bro i use tplink wn722n? which adapter should buy in low budget?

**Comment by cjb900** [comment] 2021-10-10 07:39
yes but you have the v2 of that adapter only the v1 is properly supported for wifi hacking which is why you are having issues. You can find a list of known good adapters and chipsets below. But i can't say what the cost of them will be as that all depends on where you live and whats available online or in stores around you. 

Atheros AR9271 <- present in TP-Link TL-WN722N v1 or Alfa AWUS036NHA (2.4Ghz - USB)
MediaTek MT7610U <- present in TP-Link Archer T2UH (2.4Ghz/5Ghz - USB)
MediaTek MT7612U <- present in Alfa AWUS036ACM (2.4Ghz/5Ghz - USB) (not recommended to be used on Virtual Machines, but it works very well on native Linux. The recommended Linux kernel version is 5.3 or greater). For Rpi 2/3 run this command to get the card working echo "options mt76_usb disable_usb_sg=1" > /etc/modprobe.d/mt76_usb.conf
Ralink RT2770 <- present in Alfa AWUS051NH (2.4Ghz/5Ghz - USB)
Ralink RT3070 <- present in TP-Link TL-WN7200ND or Alfa AWUS036NH (2.4Ghz - USB)
Ralink RT3572 <- present in Alfa AWUS052NHS (2.4Ghz/5Ghz - USB)
Ralink RT5372 <- present in D-Link DWA-137 (2.4Ghz - USB)
Ralink RT5378 <- present in some some unbranded cheap chinese dongles (2.4Ghz - USB)
Ralink RT5572 <- present in Panda PAU07 or Panda PAU09 (2.4Ghz/5Ghz - USB)
Realtek RTL8723BE <- present in Realtek RTL8723BE card (2.4Ghz - PCIe)

**Comment by LokotamaTheMastermind** [comment] 2021-11-05 17:07
> after install adaptor is not working at all

Hey there, could you describe further what you mean by isn't working

**Comment by Medullitus** [comment] 2022-02-02 21:02
Help please. I have the same chipset please help!!!

**Comment by cjb900** [comment] 2022-02-02 21:07
@Medullitus if you have a tplink wn722n V2/3 there is no way to get it to work in fluxion by its self. It needs VIF to be able to both create the fake AP and deauth at the same time. There is no way to get that adapter to support VIF. you will either need to buy a second one to use with fluxion or get one of the supported adapter/chipsets listed above

**Comment by Medullitus** [comment] 2022-02-02 21:18
> @Medullitus if you have a tplink wn722n V2/3 there is no way to get it to work in fluxion by its self. It needs VIF to be able to both create the fake AP and deauth at the same time. There is no way to get that adapter to support VIF. you will either need to buy a second one to use with fluxion or get one of the supported adapter/chipsets listed above

I bought this model. Can you check please? https://tr.aliexpress.com/item/1005002388387782.html?gatewayAdapt=glo2tur&spm=a2g0o.9042311.0.0.23bd4c4d76qqKs

Only monitor mode is mentioned but not the vif! Why vif isn't mentioned anywhere if it's that important feature, why????? :(((((

**Comment by cjb900** [comment] 2022-02-02 21:21
VIF is not a common feature and is not normally mentioned in descriptions. But that chipset is an RTL one so is not going to work. if you recently bought it i would return it and get one from the list above.

**Comment by Medullitus** [comment] 2022-02-02 21:33
> VIF is not a common feature and is not normally mentioned in descriptions. But that chipset is an RTL one so is not going to work. if you recently bought it i would return it and get one from the list above.

It really sucks!! I waited it for weeks!!

I couldn't find them on Aliexpress. Can you check this please? 

https://tr.aliexpress.com/item/32969457195.html?gatewayAdapt=glo2tur&spm=a2g0s.8937460.0.0.37672e0e6eYdPE

You say MediaTek MT7612U but says MediaTek MT7612UN? Would be there any difference? I wanna use it with the virtualbox by the way...

**Comment by cjb900** [comment] 2022-02-02 21:40
If the chipset is not on that list i can not say if it will work. considering the MT7612UN is similar to the MT7612U it may work but i have not seen anyone here use the MT7612UN so i can't guarantee. the best i can suggest is to stick to that list. if it not on it don't get it unless you can find something else online proving it will work and supports monitor mode, AP mode and VIF

**Comment by Medullitus** [comment] 2022-02-02 21:48
> If the chipset is not on that list i can not say if it will work. considering the MT7612UN is similar to the MT7612U it may work but i have not seen anyone here use the MT7612UN so i can't guarantee. the best i can suggest is to stick to that list. if it not on it don't get it unless you can find something else online proving it will work and supports monitor mode, AP mode and VIF

Okay bud, thank you so much. I really hate vif.. or realtek company...

**Comment by cjb900** [comment] 2022-02-02 21:54
@Medullitus I did some asking and that chipset MT7612UN should work and support VIF just like the MT7612U. But its not a 100% guarantee since the others i was asking do not have an adapter with that chipset to verify. So you would be gambling if you bought that adapter.

**Comment by Medullitus** [comment] 2022-02-02 23:29
> @Medullitus I did some asking and that chipset MT7612UN should work and support VIF just like the MT7612U. But its not a 100% guarantee since the others i was asking do not have an adapter with that chipset to verify. So you would be gambling if you bought that adapter.

Thank you so much bro! I can't find other chipsets available in Aliexpres.. Isn't there any chipset with Atheros except Atheros AR9271? It's surprising that your list is too short for both 2.5ghz and 5ghz adapters.

**Comment by cjb900** [comment] 2022-02-03 00:01
that list is of adapter/chipset that have been tested and support all the modes needed and guaranteed to work with little to no issues. So yes there are many other adapter/chipsets out there but they either do not support the modes needed or have some issue that makes them not recommended or have not been tested to know if they will work. So anything not on that list would need some documented proof showing it will work.

**Comment by OyewoleOyedeji** [comment] 2022-02-11 15:53
@Medullitus try using `Qualcomm Atheros AR9271 WiFi Adapter`, it contains the `ath9k_htc` which supports `VIF (virtual interface)` mode and best of all is natively supported by most Linux distributions. At least that is what I use and I haven't had any problem since then :smile:

**Comment by MayankJaint** [comment] 2022-03-21 06:49
> It's better to talk publicly as the others might need this in the future just run `make` in the root folder of the repository, then run `sudo make install` don't forget to install the kernel headers corresponding to your kernel version

how do i install the kernel headers
