### ISSUE TITLE
Connected clients not showing up

### ISSUE THREAD

**Issue by Boosted240** [FluxionNetwork/fluxion#97] opened 2017-08-20 04:43 UTC
### Do you want to request a *feature* or report a *bug*?
-> *Bug*

### What is the current behavior?
-> Once the AP is created, and clients connect, it won't show any clients connected. 

#### If the current behavior is a bug, please provide the steps to reproduce.
-> Start captive portal, connect to the AP, clients shows 0.  I've tried two different adapters, couple AP's, connected with a phone/laptop.  Same behavior.  Pretty certain this used to work several versions ago.

![2017-08-20_0-21-48](https://user-images.githubusercontent.com/30992370/29492124-4bd6995a-853f-11e7-8904-222d1152262e.jpg)

#### What is the expected behavior?
-> Clients should be a number connected

#### Wireless adapter:
rt2800usb       Ralink Technology, Corp. RT2770
                    *and*
ath9k_htc       Atheros Communications, Inc. AR9271 802.

#### Does it support injection?
root@kali:~# aireplay-ng --test wlan2mon
04:29:23  Trying broadcast probe requests...
04:29:24  Injection is working!
04:29:25  Found 1 AP

04:29:25  Trying directed probe requests...
04:29:25  80:26:89:1F:E7:B8 - channel: 11 - '8026891fe7b6'
04:29:26  Ping (min/avg/max): 1.736ms/26.328ms/64.743ms Power: -81.87
04:29:26  30/30: 100%

root@kali:~#

#### Fluxion version:
 FLUXIONOnlineInfo=("version=?\n" "revision=?\n")
                FLUXIONOnlineRevision=$(echo "${FLUXIONOnlineInfo[@]}" | awk -F= 'tolower($1)~/revision/{print $2}')
                                echo -ne $CRed"            New revision found! "$CYel

#### Linux version:
Linux version 4.4.50-Re4son-v7+ (root@kali-pi-dev) (gcc version 6.3.0 20170516 (Debian 6.3.0-18) ) #20 SMP Wed Jul 26 07:41:10 AEST 2017

#### Specifications:
root@kali:~/fluxion# grep -E 'FLUXIONVersion=|FLUXIONRevision=' fluxion.sh && cat /proc/version && airmon-ng && aireplay-ng wlan2 -9
FLUXIONVersion=3
FLUXIONRevision=1
Linux version 4.4.50-Re4son-v7+ (root@kali-pi-dev) (gcc version 6.3.0 20170516 (Debian 6.3.0-18) ) #20 SMP Wed Jul 26 07:41:10 AEST 2017

PHY     Interface       Driver          Chipset

phy0    wlan0           ??????          Broadcom 43430
phy1    wlan1           rt2800usb       Ralink Technology, Corp. RT2770
phy2    wlan2           ath9k_htc       Atheros Communications, Inc. AR9271 802.11n

04:33:14  Trying broadcast probe requests...
04:33:15  Injection is working!
04:33:16  Found 7 APs

root@kali:~/fluxion#

The setup is an RPi-3 w/latest Kali and the Re4son-Kernel, connected to a Wifi Pineapple Tetra.

**Comment by colmoschin94** [comment] 2017-08-20 07:40
Pretty much same here, clients can try to connect but no DHCP IP is assigned (in my case) and no client connection is showed up on the interface window =)

**Comment by deltaxflux** [comment] 2017-08-20 08:52
Well @Boosted240, thank you for your detailed issue report. I see that you have attempts on this issue. So your device stays connected or does it disconnect fast like in @colmoschin94 case. Does it work for you in earlier releases.

**Note:**
Please hide your bssid because I easily figured out that you life in Hag**stown.
-------
@colmoschin94 
Do you have this issue in earlier releases? Does every window pop up like in @Boosted240 case. Do you have pulled the latest release?

**Comment by colmoschin94** [comment] 2017-08-20 09:01
Hi Delta,
i didn't use fluxion for a while since i was busy but 3/4 weeks ago everything was working fine....about the windows....give me a minute, i'll upload a screenshot =)

**Comment by colmoschin94** [comment] 2017-08-20 09:07
here it is.....as far as i remember in the previous version of the script a dhcp page was popping up...but i can't see it now =)
![screenshot from 2017-08-20 11-03-06](https://user-images.githubusercontent.com/16521628/29493491-6ba813aa-8597-11e7-8218-27a447601f16.png)

ps. don't worry about the bssid shown...it's just a test one and the mac address is random generated =D

**Comment by MPX4132** [comment] 2017-08-20 09:17
@Boosted240 you seem to be talking about clients shown in the "FLUXION AP Authenticator" window, correct? The white list with clients that join the network? If that's what you're talking about, it's a known issue. At least, I know about it but I haven't tried fixing it. I'll take a look at it later on today, I need to sleep right now.

**Comment by deltaxflux** [comment] 2017-08-20 09:19
@MPX4132 go to bed I will take a look. 

Edit: Enable 2FA

**Comment by MPX4132** [comment] 2017-08-20 09:20
@colmoschin94 yeah, the DHCP service and the DNS are missing on that screen shot you posted. They seem to not have started. Please paste fluxion in debug mode and post some screen shots and paste the results. To run in debug mode:
```
export FLUXIONDebug=1; ./fluxion.sh
```

**Comment by MPX4132** [comment] 2017-08-20 09:22
@deltaxflux thanks man.

**Comment by deltaxflux** [comment] 2017-08-20 09:43
The issue is following line:
`	xterm -bg black -fg green $TOPLEFT -title "FLUXION AP DHCP Service" -e dhcpd -d -f -lf "$FLUXIONWorkspacePath/dhcpd.leases" -cf "$FLUXIONWorkspacePath/dhcpd.conf" $VIGW 2>&1 | tee -a "$FLUXIONWorkspacePath/clients.txt" &`

The clients.txt is everytime empty so following is also empty
`cat $FLUXIONWorkspacePath/clients.txt | grep DHCPACK | awk '{print \$5}' | sort| uniq | wc -l)`

**Comment by Boosted240** [comment] 2017-08-20 12:22
@deltaxflux
No no, everything works perfectly well for me.  I can connect, make attempts, enter the password, etc. It all works as it should.  It just doesn't show any number of clients connected.  

@MPX4132
Yeah, you have it exactly.  It's not really a super important issue, since it doesn't really effect functionality.

**Comment by deltaxflux** [comment] 2017-08-20 12:55
Hopefully fixed :D

**Comment by Boosted240** [comment] 2017-08-20 13:13
@deltaxflux 
I'll test it out in a few minutes!

**Comment by deltaxflux** [comment] 2017-08-20 14:04
Yep, I forgot to ignore the gateway adress, now fixed

**Closed by deltaxflux** 2017-08-20 14:04 UTC
Labels: bug

**Comment by marcusguita** [comment] 2017-08-21 01:43
Hi... Counter is not reset (to zero) after change for new scan... Only if closes fluxion and open again...

**Comment by MPX4132** [comment] 2017-08-21 01:57
Oh yeah, the counter file isn't deleted. We can fix that easily. We should find a better way to count clients, though. The current method isn't very resilient.

**Comment by rickshido** [comment] 2017-09-17 15:08
Hi.
I have a problem. I can successfully connect to fake AP. However, no password prompt page appears in browser, even I trying to access another page. It occurs in Android OS and Windows.

Iphone (Captive Apple) is the unique device that the password prompt page appears.

I have tried to use Flexion 2 release 9 and Flexion 3. However, no sucess.

Anyone can help me?

Thanks!

**Comment by tomford007** [comment] 2017-12-13 20:34
Same issue here with 3.8 on Kali 2017.3

**Comment by limited-root** [comment] 2017-12-17 08:29
Any improvement yet? same issue here. everything works but clients list doesnt appear and no password found!

**Comment by M1z23R** [comment] 2017-12-17 16:12
Personally i find the number of clients connected unnecessary, number of attempts is just fine, connected clients won't stay connected in any way - either they provide correct pw and fluxions stops, or they give up and call their ISP :D

**Comment by limited-root** [comment] 2017-12-17 17:38
But i dont get any password either.

**Comment by M1z23R** [comment] 2017-12-17 19:16
@limited-root Try on your own AP, a test run just to see what happens on server (hacker side) and on client's side (the victim). If everything works you don't have to worry, fluxion is a greate "wireless password phisher" but people (victims) sometimes need some very basic networking skills for the attack to work. Some people just don't understand what captive portal is.
As i said, try being both attacker and the victim and see what happens.

**Comment by deltaxflux** [comment] 2017-12-18 06:30
@limited-root

Fluxion is not indented for iligal purpose.

**Comment by TranhHoangThong** [comment] 2018-03-03 10:22
![screenshot from 2018-03-01 09-18-45 - 1](https://user-images.githubusercontent.com/37014920/36933178-5e7feffe-1f07-11e8-9203-66621f982fc6.png)
Please!! how to fix?

**Comment by deltaxflux** [comment] 2018-03-03 18:10
Make a new issue. I'm glad to help you.

**Comment by Checktheflo** [comment] 2018-03-10 09:10
Hello,
I changes the line in 479 but no clients showing for me. Can you help me?
