### ISSUE TITLE
Captive portal unreachable on rogue AP.

### ISSUE THREAD

**Issue by stevanuscolonne** [FluxionNetwork/fluxion#487] opened 2018-04-28 14:17 UTC
----

#### Read the [wiki](https://github.com/FluxionNetwork/fluxion/wiki)?
No

#### Do you want to request a *feature* or report a *bug*?
Bug

#### What is the current behaviour?
Can not load Captive Portal on target device with Internal Wifi as Fake AP hotspot, but worked with external wifi/ usb wifi (TP-LINK TL WN722N v1.0) which load Captive Portal load instanty when open browse and typing google.com

#### What do you think the expected behaviour should be?
Able to load Captive Portal on target device immediately

#### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*
#### FLUXION Info
FLUXION V4.7

#### BASH Info 
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash

#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** ath9k
**Chipset:** Qualcomm Atheros AR9485 Wireless Network Adapter (rev 01)
**Master Modes** Yes
**Injection Test:** ioctl(SIOCSIWMODE) failed: Device or resource busy
Injection is working!

#### XTerm Infos
**Version:** XTerm(331)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!

#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd

#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org

#### System Info
**Chipset:** Linux version 4.14.0-kali3-amd64 (devel@kali.org) (gcc version 7.2.0 (Debian 7.2.0-18)) #1 SMP Debian 4.14.12-2kali1 (2018-01-08)
-----

**Comment by gearcapitan** [comment] 2018-04-28 15:37
i have the same problem https://github.com/FluxionNetwork/fluxion/issues/479

**Comment by MPX4132** [comment] 2018-04-28 16:42
@stevanuscolonne @gearcapitan Can you guys try running fluxion with the `airmon-ng` flag? Just launch it like so:
```
fluxion -n
# or
fluxion --airmon-ng
```

**Comment by gearcapitan** [comment] 2018-04-28 17:36
![screenshot from 2018-04-28 12-32-49](https://user-images.githubusercontent.com/13740942/39399287-d1a7d74e-4ae0-11e8-965e-43d921feff70.png)



????????????????????????????????

**Comment by djmeero** [comment] 2018-04-28 17:43
try airmon-ng stop fluxwl0 if u want to put the interface in managed mode...

**Comment by djmeero** [comment] 2018-04-28 17:45
Oh sorry i didn't read the thread 😂 I think @MPX4132 was referring to run fluxion with --airmon-ng as a parameter?

**Comment by djmeero** [comment] 2018-04-28 17:46
Like "./fluxion.sh --airmon-ng" perhaps?

**Comment by gearcapitan** [comment] 2018-04-28 17:46
oooh ok ok, i try, i will post the result

**Comment by MPX4132** [comment] 2018-04-28 20:13
@djmeero exactly like that.

@gearcapitan You should **not** have that interface available and you should not be modifying fluxion interfaces manually. You should see something like "wlanX". You need to rename your interfaces or restart your system so it does it for you.

**Comment by MPX4132** [comment] 2018-04-29 03:07
@stevanuscolonne Can you check the web server is working? All you have to do is launch the `Captive Portal` attack as you've done before, and on the machine running fluxion, open a web browser and navigate to "http://localhost" and make sure the captive portal page loads.

**Comment by gearcapitan** [comment] 2018-04-29 14:32
![screenshot from 2018-04-29 09-28-31](https://user-images.githubusercontent.com/13740942/39407726-35e7e686-4b90-11e8-902a-8b52605b099d.png)
![photo5129709398913034168](https://user-images.githubusercontent.com/13740942/39407728-40e7e464-4b90-11e8-969b-5f295222a4ed.jpg)
![photo5129709398913034169](https://user-images.githubusercontent.com/13740942/39407729-4114d2c6-4b90-11e8-81f3-80861d0a5d9f.jpg)
whit the last update :/

**Comment by MPX4132** [comment] 2018-04-29 14:56
@gearcapitan looks like eveything’s working properly, according to those logs by fluxion on the images. There’s probably something wrong with the device you’re using for testing.

**Comment by usama7628674** [comment] 2018-04-29 15:28
@gearcapitan Live boot kali from usb and try again and see if that works for you.

**Comment by gearcapitan** [comment] 2018-04-29 18:25
![kali_linux-2018-04-29-13-21-44](https://user-images.githubusercontent.com/13740942/39409646-5b023f78-4bb0-11e8-8426-9ca7d4402cfe.png)


I tried with the last update in a completely different kali and the problem is the same, the devices do not enter the hostpot page, I also realized that devices such as laptops are not de-authenticated by the capture of the handshake or by the fake ap, but as I said the problem is the same, the website does not load, I tried to flush the dns and nothing else the problem persists.

**Comment by MPX4132** [comment] 2018-04-29 18:43
@gearcapitan You **MUST** use `http://localhost` on the fluxion host, otherwise it will not load.

**Comment by MPX4132** [comment] 2018-04-29 18:46
@gearcapitan If the target access point is multi-band capable, fluxion will not be able to jam the secondary band, meaning you must jam manually.

**Comment by gearcapitan** [comment] 2018-04-29 21:47
to see !!!, I put in the browser localhost but automatically redirect me to cptive.gateway.lan, and it stays like this, I would not be saying anything if your tubieras right, cres I'm silly or what ?, also fluxion worked perfectly in version 4.4, but then they updated it and it went to hell

**Comment by MPX4132** [comment] 2018-04-29 21:55
@gearcapitan Download [fluxion v4.4 here](https://github.com/FluxionNetwork/fluxion/tree/74d35a64cdcbcc590785a736c4ee0f28859af172) and check if the issues persist.

**Comment by MPX4132** [comment] 2018-04-30 00:30
@gearcapitan thank you for all the info you’ve posted, I appreciate the help. Can you please open a new issue with the issue you’ve mentioned and showed here so we can continue there? We might be able to gather more data. Please run the diagnostics script and paste it where the issue template says (at the very bottom).

To run the diagnostics script, just do:
```
./scripts/diagnostics.sh INTERFACE
# Make sure to replace interface with your wlanX interface.
```

**Comment by gearcapitan** [comment] 2018-04-30 02:57
#### FLUXION Info
FLUXION V4.7


#### BASH Info 
GNU bash, versión 4.4.19(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
Licencia GPLv3+: GPL de GNU versión 3 o posterior <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /bin/bash


#### Interface (fluxwl0) Info 
**Device**: phy0
**Driver:** rt2800usb
**Chipset:** Ralink Technology, Corp. RT2870/RT3070
**Master Modes** Yes
**Injection Test:** Injection is working!


#### XTerm Infos
**Version:** XTerm(331)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.6
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2016, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info

  Aircrack-ng 1.2 rc4 - (C) 2006-2015 Thomas d'Otreppe
  http://www.aircrack-ng.org


#### System Info
**Chipset:** Linux version 4.15.0-kali2-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-11)) #1 SMP Debian 4.15.11-1kali1 (2018-03-21)












![kali_linux-2018-04-29-21-56-46](https://user-images.githubusercontent.com/13740942/39414035-43b522de-4bf8-11e8-8eef-d05e892afddb.png)

**Comment by rad4day** [comment] 2018-04-30 04:41
@gearcapitan 
I could imagine it is related to some changes I made when I cleaned up the iptables rules and the dns server script.

To test this, clone the most recent fluxion via git and then execute
```git revert -n ab1681d -m1```
 this will revert the merge commit ab1681d from @deltaxflux and thereby undo my changes. 
If it works after the revert, we know what's probably causing the issue.

**Comment by MPX4132** [comment] 2018-04-30 07:12
Confirmed with a DNS test, unreachable externally. It's a combination of problems between the DNS and NAT rules, I'm reverting the commit.

**Comment by MPX4132** [comment] 2018-04-30 07:17
@gearcapitan Checkout the latest version on the repository and let us know if anything changed.

**Comment by rad4day** [comment] 2018-04-30 09:16
Still funny how it worked for me while testing though

**Comment by MPX4132** [comment] 2018-04-30 13:55
@rad4day It was working for me as well, I’ll have a closer look today.

**Comment by MPX4132** [comment] 2018-04-30 14:06
@stevanuscolonne seems like your wireless device was experiencing issues.

> Injection Test: ioctl(SIOCSIWMODE) failed: Device or resource busy
> Injection is working!

**Comment by gearcapitan** [comment] 2018-05-01 05:59
because the truth is that the only version that has served me is the 4.4, from then on pure failures, the truth is that I don't know if you require another type of antenna or hardware now, because in fact, the handshake takes a long time to get compared to version 4.4 and previous, i.e. the handshake I realize that the handshake is not configured in the ap channel to get the handshake and it is difficult to channel itself to the ap channel and also makes few deauthentications, and in the end when I pick up my hostpot or fake ap, in any case the clients do not connect to the phishing page, i.e. the page simply does not load is blank, but it is more of the same thing, these errors have already been reported with screen inaccuracies, better tell me which antenna they recommend?

**Comment by MPX4132** [comment] 2018-05-01 08:45
@gearcapitan The hardware requirements haven't changed man, however, I just noticed your wireless device is using the "rt2800usb" driver, which is known to have issues. Go to the issues section and look that driver up. I'm positive we've found it's got issues with virtual interfaces. I develop and test fluxion with a AWUS036NHA, which uses the `ath9k_htc`. So long as you use a wireless device with that driver you should be good. I also have a WNA1100 which also uses the `ath9k_htc` driver and it also works great.

**Comment by usama7628674** [comment] 2018-05-01 10:58
@MPX4132 Then why version 4.4 is working for him?That's the question now.

**Comment by MPX4132** [comment] 2018-05-01 11:50
@usama7628674 If I remember correctly, the device he's using only works with airbase-ng, which works, but it's super slow. We need to investigate more if he's still having issues though, and he can't get the latest versions to work for him. Nothing major has changed that would affect the core of fluxion. The only major change happened between fluxion v3 to fluxion v4. I know that's the case because I designed both versions. Unless someone committed something between then and now that broke something, but I'm not sure. Do you have any issues like he does?

**Comment by usama7628674** [comment] 2018-05-01 12:00
@MPX4132 I'm thinking maybe he should try airgeddon script.It does have evil twin attack method like fluxion.If that script works then perhaps there is something wrong with fluxion.

**Comment by usama7628674** [comment] 2018-05-01 12:03
@MPX4132 I also use awus036nha.I haven't tried fluxion for quite some time.I'll give a shot tomorrow and share the result here.

**Comment by usama7628674** [comment] 2018-05-02 06:46
@MPX4132 Unfortunately it's not working for me as well.I didn't use awus036nha but internal card (atheros ar9565).I was able to capture handshakes but captive portal wasn't working.It's stuck at **Starting captive portal**.Then I tried airgeddon script which has evil twin method with captive portal as fluxion and it worked(same internal card).I noticed something fluxion isn't restoring interface names back to original ones.

**Comment by MPX4132** [comment] 2018-05-02 15:11
@usama7628674 sound so like you’re having issues with your device’s driver. It sounds like the driver hanged and your system froze or something. Unplugging and replugging the wireless device usually works.

**Comment by MPX4132** [comment] 2018-05-02 16:38
@usama7628674 @gearcapitan I went over every single change to the repository between fluxion 4.4 and the current version. I can't find anything that affects previous functionality. Seems like both of you, or just me, is falling for confirmation bias.

**Comment by usama7628674** [comment] 2018-05-03 03:57
@MPX4132 Ok now it's working fine.Captive portal does load on my device with internal and as well as with external card.

**Comment by stevanuscolonne** [comment] 2018-05-03 12:42
@Matias sorry for late reply. Just have time to read email since i've important project at the office. Will try your suggestion as soon as i have leisure time.

Sent from Yahoo Mail on Android 
 
  On Sun, Apr 29, 2018 at 10:07, Matias Barcenas<notifications@github.com> wrote:   
@stevanuscolonne Can you check the web server is working? All you have to do is launch the Captive Portal attack as you've done before, and on the machine running fluxion, open a web browser and navigate to "http://localhost" and make sure the captive portal page loads.

**Comment by MPX4132** [comment] 2018-05-03 20:11
@stevanuscolonne that won’t work anymore. Just go ahead and try to run fluxion regularly again. We made a couple of changes.

**Comment by MPX4132** [comment] 2018-05-03 20:12
@stevanuscolonne

**Comment by stevanuscolonne** [comment] 2018-05-05 03:31
@Matias noted will try tonight (GMT +7) and will give feedback soon. Thank you for responses & support.

Sent from Yahoo Mail on Android 
 
  On Fri, May 4, 2018 at 3:11, Matias Barcenas<notifications@github.com> wrote:   
@stevanuscolonne that won’t work anymore. Just go ahead and try to run fluxion regularly again. We made a couple of changes.

**Comment by celik869013** [comment] 2018-05-09 08:05
I'm running the app but you can help me with the captive gatavey link not starting

**Comment by vampireactual** [comment] 2018-05-10 01:06
I also have the TL-WN722N wireless card, I have found that if you skip or disable target tracking on the wifi card, it totally fixes the problem

**Comment by vampireactual** [comment] 2018-05-10 02:28
I tried both, when I used two it worked. With one, it didn't.

On May 9, 2018 19:20, "Matias Barcenas" <notifications@github.com> wrote:

@vampireactual <https://github.com/vampireactual> When you were using
target tracking, were you using two separate wireless cards/devices?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/FluxionNetwork/fluxion/issues/487#issuecomment-387931747>,
or mute the thread

**Comment by MPX4132** [comment] 2018-05-10 02:30
@vampireactual Yeah, that's why I put a warning on there. You can't use virtual interfaces for target tracking. A virtual interface is a logical secondary interface adding on to the original interface that a wireless device has. You can ONLY use target tracking if you've got two physical devices. There could be drivers that support three virtual interfaces, so if you've got a rare card that can do that, good for you, but more than likely it can only do a maximum of two.

**Comment by vampireactual** [comment] 2018-05-10 02:31
I do have two physical devices.

**Comment by MPX4132** [comment] 2018-05-10 02:32
Right, that's why you said it worked with two. That's great, but I'm letting you know it will very likely not work **with a single wireless device** having to do everything, monitor, deauthenticate, and channel scan.

**Comment by stevanuscolonne** [comment] 2018-05-12 09:30
Sorry all I forgot to update that this error previous solved for me but facing another issue that i just opened.

**Closed** 2018-05-12 13:33 UTC
Labels: Need More Info
