### ISSUE TITLE
AN automatically attack restart option with static bssid 

### ISSUE THREAD

**Issue by minanagehsalalma** [FluxionNetwork/fluxion#247] opened 2017-11-11 22:39 UTC
### Do you want to request a *feature* or report a *bug*?
*a feature*
what about to make the attack  automatically restart after a few minutes (let the user choose the time ) and start with  the same bssid  used in the first time to fix the channel change after victim ap restart in case of having one wireless adapter (and make it optional )
😀😊😊

**Comment by MPX4132** [comment] 2017-11-12 05:00
This would definitely work, but if we can make it dynamically change channels, that would be great.

**Comment by minanagehsalalma** [comment] 2017-11-12 09:11
No.  It's impossible to dynamically change the channel without stoping  the
attack !!!

**Comment by MPX4132** [comment] 2017-11-12 10:29
That may not be true, by accessing low-level data, or diagnostics info, from the wireless device we might be able to perform a quick scan while operating in master mode.

**Comment by evgeniy4587** [comment] 2017-11-12 12:08
It might be realized in some do while cycle. 
1. monitoring/checking target AP channel.
2. if channel changed stop fake AP
3. check current channel
4. run fake AP.

Sorry if I wrote obvious things.

**Comment by MPX4132** [comment] 2017-11-12 18:33
Yeah, it would work something like that. I need to look into it to find out if it's possible.

**Comment by minanagehsalalma** [comment] 2017-11-12 20:02
@evgeniy4587 
you missed this 
3.check current channel
4. run the fake ap and mdk3 Operation on the new channel . as i have said

**Comment by strasharo** [comment] 2017-11-12 20:37
Duplicate of https://github.com/FluxionNetwork/fluxion/issues/152, please  stop spamming over and over again with the same stuff.

**Closed by strasharo** 2017-11-12 20:37 UTC

**Comment by minanagehsalalma** [comment] 2017-11-12 20:54
Bro but this a little bit different.  Not smart like the #152 one.  It
simple and Primitive.   It should be detached  from the other one  ....
 😞😞
